/**
 * Unit Tests: getUserById (Bug API-404 fix)
 *
 * Generated by Unit Test Generator Agent.
 * FIRST principles applied per skills/unit-tests-FIRST.md:
 *   Fast        – uses supertest with in-process server; no real network calls
 *   Independent – each test is isolated; no shared mutable state
 *   Repeatable  – no real I/O or time-dependent values
 *   Self-validating – every test has explicit expect assertions
 *   Timely      – generated immediately after bug fix applied
 */

const request = require('supertest');
const app = require('../server');

describe('GET /api/users/:id', () => {
  // ── Positive tests (fixed behaviour) ──────────────────────────────────────

  test('returns 200 and correct user for valid numeric ID 123', async () => {
    const res = await request(app).get('/api/users/123');
    expect(res.status).toBe(200);
    expect(res.body).toEqual({ id: 123, name: 'Alice Smith', email: 'alice@example.com' });
  });

  test('returns 200 and correct user for valid numeric ID 456', async () => {
    const res = await request(app).get('/api/users/456');
    expect(res.status).toBe(200);
    expect(res.body).toEqual({ id: 456, name: 'Bob Johnson', email: 'bob@example.com' });
  });

  test('returns 200 and correct user for valid numeric ID 789', async () => {
    const res = await request(app).get('/api/users/789');
    expect(res.status).toBe(200);
    expect(res.body).toEqual({ id: 789, name: 'Charlie Brown', email: 'charlie@example.com' });
  });

  // ── Negative tests (old broken behaviour must no longer occur) ────────────

  test('REGRESSION: string "123" route param now resolves to correct user (was 404 before fix)', async () => {
    // Before the fix: users.find(u => u.id === "123") always returned undefined → 404
    // After the fix:  parseInt("123", 10) === 123 → user found → 200
    const res = await request(app).get('/api/users/123');
    expect(res.status).not.toBe(404);
    expect(res.status).toBe(200);
  });

  // ── Edge case tests ────────────────────────────────────────────────────────

  test('returns 404 for non-existent numeric ID 999', async () => {
    const res = await request(app).get('/api/users/999');
    expect(res.status).toBe(404);
    expect(res.body).toEqual({ error: 'User not found' });
  });

  test('returns 404 for non-numeric ID "abc"', async () => {
    // parseInt("abc", 10) → NaN; NaN === <any number> is false → no match → 404
    const res = await request(app).get('/api/users/abc');
    expect(res.status).toBe(404);
    expect(res.body).toEqual({ error: 'User not found' });
  });

  test('returns 404 for ID 0 (not in users array)', async () => {
    const res = await request(app).get('/api/users/0');
    expect(res.status).toBe(404);
    expect(res.body).toEqual({ error: 'User not found' });
  });

  test('returns 404 for negative ID -1', async () => {
    const res = await request(app).get('/api/users/-1');
    expect(res.status).toBe(404);
    expect(res.body).toEqual({ error: 'User not found' });
  });

  test('returns 404 for floating-point ID 123.5 (parseInt truncates to 123, matches user)', async () => {
    // parseInt("123.5", 10) → 123 which matches Alice Smith
    // This documents the current behaviour — parseInt truncation
    const res = await request(app).get('/api/users/123.5');
    expect(res.status).toBe(200);
    expect(res.body.id).toBe(123);
  });

  test('returns 404 for very large numeric ID', async () => {
    const res = await request(app).get('/api/users/99999999999999');
    expect(res.status).toBe(404);
    expect(res.body).toEqual({ error: 'User not found' });
  });

  test('returns 404 for special characters in ID', async () => {
    const res = await request(app).get('/api/users/%24%7Bjndi%7D');
    expect(res.status).toBe(404);
    expect(res.body).toEqual({ error: 'User not found' });
  });

  test('returns 404 for SQL injection attempt in ID', async () => {
    const res = await request(app).get("/api/users/1'%20OR%20'1'='1");
    expect(res.status).toBe(404);
    expect(res.body).toEqual({ error: 'User not found' });
  });
});

describe('GET /api/users', () => {
  test('returns all users as an array', async () => {
    const res = await request(app).get('/api/users');
    expect(res.status).toBe(200);
    expect(Array.isArray(res.body)).toBe(true);
    expect(res.body).toHaveLength(3);
  });
});
